#!/bin/bash

wget https://downloads.lightbend.com/scala/2.13.1/scala-2.13.1.deb -P ~/Downloads/
wget https://piccolo.link/sbt-1.3.2.zip -P ~/Downloads

bosh add-blob ~/Downloads/scala-2.13.1.deb scala/scala-2.13.1.deb 
bosh add-blob ~/Downloads/sbt-1.3.2.zip scala/sbt-1.3.2.zip
